# Generated by Django 4.2.17 on 2024-12-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelcontent',
            name='title',
            field=models.CharField(),
        ),
    ]
